/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.trainbooking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Legion
 */
public class admintrainedit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(admintrainedit.class.getName());

    /**
     * Creates new form admintrainedit
     */
    public admintrainedit() {
        initComponents();
        tableloaddata();
    }
    
    //cleardetails
    public void cleardetails(){
        trainno.setText(null);
        dstart.setText(null);
        destination.setText(null);
        ddate.setText(null);
        dtime.setText(null);
        price.setText(null);
    }
    public void tableloaddata(){
        DefaultTableModel table=(DefaultTableModel)traindet.getModel();
        table.setRowCount(0);
        
        try (Connection conect = DatabaseConnection.getConnection();
        PreparedStatement prt = conect.prepareStatement("SELECT trainno,dstart,destination,ddate,dtime,price FROM trains");
        ResultSet abc=prt.executeQuery()){
            
            while(abc.next()){
                table.addRow(new Object[]{
                    abc.getString("trainno"),
                    abc.getString("dstart"),
                    abc.getString("destination"),
                    abc.getString("ddate"),
                    abc.getString("dtime"),
                    abc.getString("price"),

                });
            }
        }catch (SQLException ex){
        logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);
                
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        traindet = new javax.swing.JTable();
        delbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        trainno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dstart = new javax.swing.JTextField();
        destination = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ddate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dtime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        clrbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        traindet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Train no", "Start", "Destination", "Date", "Time", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        traindet.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        traindet.getTableHeader().setReorderingAllowed(false);
        traindet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                traindetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(traindet);

        delbtn.setText("Delete");
        delbtn.addActionListener(this::delbtnActionPerformed);

        addbtn.setText("Add");
        addbtn.addActionListener(this::addbtnActionPerformed);

        editbtn.setText("Update");
        editbtn.addActionListener(this::editbtnActionPerformed);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Add,Edit and Update ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Train no");

        trainno.addActionListener(this::trainnoActionPerformed);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Start");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destination");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price");

        clrbtn.setText("Clear");
        clrbtn.addActionListener(this::clrbtnActionPerformed);

        backbtn.setText("Back");
        backbtn.addActionListener(this::backbtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dstart, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(destination)
                                    .addComponent(ddate)
                                    .addComponent(dtime)
                                    .addComponent(trainno))
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addbtn)
                            .addComponent(editbtn))
                        .addComponent(delbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backbtn))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(trainno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trainnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainnoActionPerformed

    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtnActionPerformed
        // TODO add your handling code here:
        cleardetails();
    }//GEN-LAST:event_clrbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String trainnumber=trainno.getText().trim();
        String station=dstart.getText().trim();
        String end=destination.getText().trim();
        String date=ddate.getText().trim();
        String time=dtime.getText().trim();
        String tprice=price.getText().trim();
        if (trainnumber.isBlank()||station.isBlank()||end.isBlank()||date.isBlank()||time.isBlank()||tprice.isBlank()) 
        {
            JOptionPane.showMessageDialog(this,"Please fill in all required fields.");
            return;
        }
        try (Connection conect = DatabaseConnection.getConnection();
        PreparedStatement trn = conect.prepareStatement(
         "INSERT INTO trains(trainno,dstart,destination,ddate,dtime,price)VALUES(?,?,?,?,?,?)"))
        {
            trn.setString(1,trainnumber);
            trn.setString(2,station);
            trn.setString(3,end);
            trn.setString(4,date);
            trn.setString(5,time);
            trn.setString(6,tprice);
           

            int k=trn.executeUpdate();

            if (k>0) 
            {
                JOptionPane.showMessageDialog(this,"Details added Successful!y");
                cleardetails();
                tableloaddata();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Failed to add details");
            }
        }
        catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);   
        }


    }//GEN-LAST:event_addbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        String trainnumber=trainno.getText().trim();
        String station=dstart.getText().trim();
        String end=destination.getText().trim();
        String date=ddate.getText().trim();
        String time=dtime.getText().trim();
        String tprice=price.getText().trim();
        if (trainnumber.isBlank()||station.isBlank()||end.isBlank()||date.isBlank()||time.isBlank()||tprice.isBlank()) 
        {
            JOptionPane.showMessageDialog(this,"Please select a row or fill the rows.");
            return;
        }
        try (Connection conect = DatabaseConnection.getConnection();
        PreparedStatement trn = conect.prepareStatement(
         "UPDATE trains SET dstart=?,destination=?,ddate=?,dtime=?,price=? WHERE trainno=?"))
        {
            trn.setString(1,station);
            trn.setString(2,end);
            trn.setString(3,date);
            trn.setString(4,time);
            trn.setString(5,tprice);
            trn.setString(6,trainnumber);

           

            int k=trn.executeUpdate();

            if (k>0) 
            {
                JOptionPane.showMessageDialog(this,"Details updated Successful!y");
                cleardetails();
                tableloaddata();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Failed to update details");
            }
        }
        catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);   
        }

    }//GEN-LAST:event_editbtnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:
        String trainnumber=trainno.getText().trim();
        String station=dstart.getText().trim();
        String end=destination.getText().trim();
        String date=ddate.getText().trim();
        String time=dtime.getText().trim();
        String tprice=price.getText().trim();
        if (trainnumber.isBlank()||station.isBlank()||end.isBlank()||date.isBlank()||time.isBlank()||tprice.isBlank()) 
        {
            JOptionPane.showMessageDialog(this,"Please select a row or fill the rows.");
            return;
        }
        try (Connection conect = DatabaseConnection.getConnection();
        PreparedStatement trn = conect.prepareStatement(
         "DELETE FROM trains WHERE trainno=? AND dstart=? AND destination=? AND ddate=? AND dtime=? AND price=?"))
        {
            trn.setString(1,trainnumber);
            trn.setString(2,station);
            trn.setString(3,end);
            trn.setString(4,date);
            trn.setString(5,time);
            trn.setString(6,tprice);
      

            int k=trn.executeUpdate();

            if (k>0) 
            {
                JOptionPane.showMessageDialog(this,"Details deleted Successful!y");
                cleardetails();
                tableloaddata();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Failed to delete details");
            }
        }
        catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);   
        }

    }//GEN-LAST:event_delbtnActionPerformed

    private void traindetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_traindetMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tablerow=(DefaultTableModel)traindet.getModel();
        int row=traindet.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this,"Please select a row.");
            return;
        }
        else{
        trainno.setText(tablerow.getValueAt(row,0).toString());
        dstart.setText(tablerow.getValueAt(row,1).toString());
        destination.setText(tablerow.getValueAt(row,2).toString());
        ddate.setText(tablerow.getValueAt(row,3).toString());
        dtime.setText(tablerow.getValueAt(row,4).toString());
        price.setText(tablerow.getValueAt(row,5).toString());

        }

    }//GEN-LAST:event_traindetMouseClicked

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Admindashboard back=new Admindashboard();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new admintrainedit().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton clrbtn;
    private javax.swing.JTextField ddate;
    private javax.swing.JButton delbtn;
    private javax.swing.JTextField destination;
    private javax.swing.JTextField dstart;
    private javax.swing.JTextField dtime;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JTable traindet;
    private javax.swing.JTextField trainno;
    // End of variables declaration//GEN-END:variables
}
   

