/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.trainbooking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Legion
 */
public class Canceloder extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Canceloder.class.getName());

    /**
     * Creates new form Canceloder
     */
    private String loguser;
    public Canceloder() {
        initComponents();
    }
    
    public Canceloder(String username) {
        initComponents();
        this.loguser=username;
        tableloaddata();

    }
    public void cleardetails(){
        oderid.setText(null);

    }
    
    public void tableloaddata(){
        DefaultTableModel table=(DefaultTableModel)odertble.getModel();
        table.setRowCount(0);
        
        try (Connection conect = DatabaseConnection.getConnection();
        PreparedStatement prt = conect.prepareStatement("SELECT id,trainno,dstart,destination,ddate,dtime,dclass,cperson,price,tperson,total,status FROM bookings WHERE username=?")){
        prt.setString(1,this.loguser);
        ResultSet abc=prt.executeQuery();
            
            while(abc.next()){
                table.addRow(new Object[]{
                    abc.getString("id"),
                    abc.getString("trainno"),
                    abc.getString("dstart"),
                    abc.getString("destination"),
                    abc.getString("ddate"),
                    abc.getString("dtime"),
                    abc.getString("dclass"),
                    abc.getString("cperson"),
                    abc.getString("price"),
                    abc.getString("tperson"),
                    abc.getString("total"),
                    abc.getString("status"),

                });
            }
        }catch (SQLException ex){
        logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);
                
        }   
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        odertble = new javax.swing.JTable();
        delodrbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        oderid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bckbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        odertble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Oder id", "Train no", "Start", "Destination", "Date", "Time", "Class", "Class Price", "Price", "Amount", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        odertble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odertbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(odertble);

        delodrbtn.setText("Confirm");
        delodrbtn.addActionListener(this::delodrbtnActionPerformed);

        jLabel1.setText("Cancel order");

        oderid.setEditable(false);

        jLabel2.setText("Oder id");

        bckbtn.setText("Back");
        bckbtn.addActionListener(this::bckbtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bckbtn)
                        .addGap(230, 230, 230)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oderid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delodrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bckbtn)
                        .addGap(1, 1, 1)))
                .addComponent(delodrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delodrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delodrbtnActionPerformed
        // TODO add your handling code here:
        String ordernumber=oderid.getText().trim();
        
        if (ordernumber.isBlank()) 
        {
            JOptionPane.showMessageDialog(this,"Please select oder first.");
            return;
        }
        try (Connection conect = DatabaseConnection.getConnection();
        PreparedStatement trn = conect.prepareStatement(
         "UPDATE bookings SET status='Cancelled' WHERE id=? AND username=?"))
        {
            trn.setString(1,ordernumber);
            trn.setString(2,this.loguser);

          
            int k=trn.executeUpdate();

            if (k>0) 
            {
                JOptionPane.showMessageDialog(this,"Oder cancelled succefully");
                cleardetails();
                tableloaddata();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Failed to cancel order");
            }
        }
        catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);   
        }
        
        
    }//GEN-LAST:event_delodrbtnActionPerformed

    private void odertbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odertbleMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tablerow=(DefaultTableModel)odertble.getModel();
        int row=odertble.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this,"Please select a row.");
            return;
        }
        else{
        oderid.setText(tablerow.getValueAt(row,0).toString());

        }
    }//GEN-LAST:event_odertbleMouseClicked

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        // TODO add your handling code here:
        Usersdashboard pass = new Usersdashboard(this.loguser);
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bckbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Canceloder().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckbtn;
    private javax.swing.JButton delodrbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField oderid;
    private javax.swing.JTable odertble;
    // End of variables declaration//GEN-END:variables
}
