/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.trainbooking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Legion
 */
public class Canceloder extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Canceloder.class.getName());

    /**
     * Creates new form Canceloder
     */
    private String loguser;
    public Canceloder() {
        initComponents();
    }
    
    public Canceloder(String username) {
        initComponents();
        this.loguser=username;
        tableloaddata();

    }
    public void cleardetails(){
        oderid.setText(null);

    }
    
    public void tableloaddata(){
        DefaultTableModel table=(DefaultTableModel)odertble.getModel();
        table.setRowCount(0);
        
        try (Connection conect = DatabaseConnection.getConnection();
        PreparedStatement prt = conect.prepareStatement("SELECT id,trainno,dstart,destination,ddate,dtime,dclass,cperson,price,tperson,total,status FROM bookings WHERE username=?")){
        prt.setString(1,this.loguser);
        ResultSet abc=prt.executeQuery();
            
            while(abc.next()){
                table.addRow(new Object[]{
                    abc.getString("id"),
                    abc.getString("trainno"),
                    abc.getString("dstart"),
                    abc.getString("destination"),
                    abc.getString("ddate"),
                    abc.getString("dtime"),
                    abc.getString("dclass"),
                    abc.getString("cperson"),
                    abc.getString("price"),
                    abc.getString("tperson"),
                    abc.getString("total"),
                    abc.getString("status"),

                });
            }
        }catch (SQLException ex){
        logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);
                
        }   
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.putClientProperty("FlatLaf.style", "arc: 30");
        bckbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        oderid = new javax.swing.JTextField();
        delodrbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        odertble = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bckbtn.setBackground(new java.awt.Color(255, 0, 51));
        bckbtn.setText("Back");
        bckbtn.addActionListener(this::bckbtnActionPerformed);

        jLabel2.setText("Oder id");

        oderid.setEditable(false);

        delodrbtn.setBackground(new java.awt.Color(51, 0, 255));
        delodrbtn.setForeground(new java.awt.Color(255, 255, 255));
        delodrbtn.setText("Confirm");
        delodrbtn.addActionListener(this::delodrbtnActionPerformed);

        jLabel1.setText("Cancel reservation");

        odertble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Oder id", "Train no", "Start", "Destination", "Date", "Time", "Class", "Class Price", "Price", "Amount", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        odertble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odertbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(odertble);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Cancel reservation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(bckbtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(delodrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(533, 533, 533)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oderid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 9, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bckbtn)
                    .addComponent(delodrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void delodrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delodrbtnActionPerformed
        // TODO add your handling code here:
        String ordernumber=oderid.getText().trim();
        
        if (ordernumber.isBlank()) 
        {
            JOptionPane.showMessageDialog(this,"Please select oder first.");
            return;
        }
        try (Connection conect = DatabaseConnection.getConnection();
        PreparedStatement trn = conect.prepareStatement(
         "UPDATE bookings SET status='Cancelled' WHERE id=? AND username=?"))
        {
            trn.setString(1,ordernumber);
            trn.setString(2,this.loguser);

          
            int k=trn.executeUpdate();

            if (k>0) 
            {
                JOptionPane.showMessageDialog(this,"Oder cancelled succefully");
                cleardetails();
                tableloaddata();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Failed to cancel order");
            }
        }
        catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);   
        }
        
        
    }//GEN-LAST:event_delodrbtnActionPerformed

    private void odertbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odertbleMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tablerow=(DefaultTableModel)odertble.getModel();
        int row=odertble.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this,"Please select a row.");
            return;
        }
        else{
        oderid.setText(tablerow.getValueAt(row,0).toString());

        }
    }//GEN-LAST:event_odertbleMouseClicked

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        // TODO add your handling code here:
        Usersdashboard pass = new Usersdashboard(this.loguser);
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bckbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Canceloder().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckbtn;
    private javax.swing.JButton delodrbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField oderid;
    private javax.swing.JTable odertble;
    // End of variables declaration//GEN-END:variables
}
